@url = http://localhost:1234

get {{url}}/
###
post {{url}}/
Content-Type: application/json

{
    "regno": "KA-01-AB-1234",
    "brand": "Suzuki",
    "model": "Swift",
    "color": "Red",
    "price": 500000
}
###
patch {{url}}/TN01GH3456
Content-Type: application/json

{
    "color": "Blue",
    "price": 850000
}
###
delete {{url}}/KA-01-AB-1234
###
delete {{url}}/TN01GH3456